version: '3'
services:
  proxy:
    build: ./proxy
    container_name: "app_proxy"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - "app"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      amby_app_net:
        ipv4_address: 172.16.238.10
    tty: true

  app:
    build: ./app
    container_name: app_go
    ports:
      - "8080"
    depends_on:
      - "db"
    tty: true
    volumes:
      - "./app/amby:/go/src/github.com/eifandevs/amby"
    networks:
      amby_app_net:
        ipv4_address: 172.16.238.11

  db:
    build: ./db
    container_name: app_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: amby
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/log:/var/log/mysql
    networks:
      amby_app_net:
        ipv4_address: 172.16.238.12

networks:
  amby_app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/16