openapi: 3.0.0
info:
  version: 1.0.0
  title: REST sample
paths:
  /api/login:
    post:
      tags:
        - login
      summary: ログインする
      description: モデルUserにレコードを追加し、トークンを返却する。登録されている場合もトークンを返却する。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  description: データ
                  properties:
                    mail:
                      type: string
                      example: aaa@ggg
      responses:
        '200':
          description: アクセストークンを返します。
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: 1000
                  errorMessage:
                    type: string
                    example: 内部エラー
                  data:
                    type: object
                    properties:
                      accessToken:
                        type: string
                        example: aaeefeifufeofefjk
  /api/favorite:
    post:
      tags:
        - favorite
      summary: お気に入り操作
      description: お気に入りの登録・削除
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                  description: データ
                  properties:
                    mail:
                      type: string
                      example: aaa@ggg
      responses:
        '200':
          description: アクセストークンを返します。
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: 1000
                  errorMessage:
                    type: string
                    example: 内部エラー
                  data:
                    type: object
                    properties:
                      accessToken:
                        type: string
                        example: aaeefeifufeofefjk
